### ISSUE TITLE
Update identity.war with Latest to Patch Security Vulnerability and Push to Dockerhub

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/docker-oxtrust#10]
https://github.com/GluuFederation/docker-oxtrust/blob/3.1.3/Dockerfile#L57

Should be:

```
ENV OX_VERSION 3.1.3.1.Final
ENV OX_BUILD_DATE 2018-08-10
ENV OXTRUST_DOWNLOAD_URL https://ox.gluu.org/maven/org/xdi/oxtrust-server/${OX_VERSION}/oxtrust-server-${OX_VERSION}.war
```

http://ox.gluu.org/maven/org/xdi/oxtrust-server/3.1.3.1.Final/oxtrust-server-3.1.3.1.Final.war

**Comment by iromli** [comment]
Code updated. Image has been pushed to docker hub.
