### ISSUE TITLE
Distribute customization dir across all containers

### ISSUE THREAD

**Issue by iromli** [GluuFederation/docker-oxtrust#17]
We may utilize JCR to distribute customization as per https://gluu.org/docs/gluu-server/operation/custom-design/.

**Comment by moabu** [comment]
Yes we need to sync in `/opt/gluu/jetty/identity/custom/`

**Comment by iromli** [comment]
Implemented in https://github.com/GluuFederation/docker-oxtrust/commit/14b4f6411aaf11ada5f6b20075927fb06efbae8e
