### ISSUE TITLE
Give User Control of Memory Max

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/docker-oxtrust#3]
Currently the default on both oxAuth and oxTrust is set to use up to 6GB of RAM. While testing rkt as the orchestrator, this caused issues with excessive memory usage and failure. There needs to be a way to control that max via environment variables.

From oxAuth:

```
exec java -jar /opt/jetty/start.jar -server \
    -Xms256m -Xmx4096m -XX:+DisableExplicitGC \
    -Dgluu.base=/etc/gluu \
    -Dserver.base=/opt/gluu/jetty/oxauth \
    -Dlog.base=/opt/gluu/jetty/oxauth \
    -Dpython.home=/opt/jython
```
From oxTrust:

```
exec java -jar /opt/jetty/start.jar -server \
    -Xms256m -Xmx2048m -XX:+DisableExplicitGC \
    -Dgluu.base=/etc/gluu \
    -Dserver.base=/opt/gluu/jetty/identity \
    -Dlog.base=/opt/gluu/jetty/identity \
    -Dorg.eclipse.jetty.server.Request.maxFormContentSize=50000000 \
    -Dpython.home=/opt/jython \
    jetty.http.port=8082
```

The default minimum per service in Gluu Server CE are as follows:

oxAuth:

```
-Xms256m -Xmx1073m
```

oxTrust:

```
-Xms256m -Xmx715m 
```

I believe the solution is an environment variable that can be assigned on startup. These variables should be taken by `entrypoint.sh`. This should work on the oxAuth and oxTrust image.

**Comment by yurem** [comment]
Additionally with Java 1.8 we need to specify `-XX:MaxMetaspaceSize` too.

CE setup uses `memory` property from [this ](https://github.com/GluuFederation/community-edition-setup/blob/master/setup.py#L174) dictionary to split allowed memory between apps. Also there is upper limit here. This [method](https://github.com/GluuFederation/community-edition-setup/blob/master/setup.py#L3201) it uses to prepare jetty JVM options. Example: [/etc/default/oxauth](https://github.com/GluuFederation/community-edition-setup/blob/master/templates/jetty/oxauth#L3).

This file has 3 memory options:
```
-Xms%(oxauth_min_heap_mem)sm -Xmx%(oxauth_max_heap_mem)sm -XX:MaxMetaspaceSize=%(oxauth_max_meta_mem)sm
```

Additionally we pass `-XX:+DisableExplicitGC` to prohibit programmatic Garbage collections calls.

**Comment by iromli** [comment]
Docker has feature to specify max. memory used by a container through `docker run -m` option, or `mem_limit` in docker-compose file. Note that the entrypoint of oxAuth and oxTrust will be modified. Apparently, the `-Xmx` Java option doesn't honour memory limit of the container. Instead we will need to use `-XX:+UnlockExperimentalVMOptions`, `-XX:+UseCGroupMemoryLimitForHeap`, and `-XX:MaxRAMFraction` options.

```sh
exec java -jar /opt/jetty/start.jar \
    -server \
    -XX:+UnlockExperimentalVMOptions \
    -XX:+UseCGroupMemoryLimitForHeap \
    -XX:MaxRAMFraction=$GLUU_MAX_RAM_FRACTION \
    -XX:+DisableExplicitGC \
    -Dgluu.base=/etc/gluu \
    -Dserver.base=/opt/gluu/jetty/oxauth \
    -Dlog.base=/opt/gluu/jetty/oxauth \
    -Dpython.home=/opt/jython
```

**Comment by iromli** [comment]
The code and images for oxAuth and oxTrust have been updated.

**Comment by iromli** [comment]
Closing this issue. Feel free to re-open if it doesn't work.
