### ISSUE TITLE
The folders i18n and libs should be exposed as volumes to allow resources and libraries customization

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/docker-oxtrust#6]
# Description
1. The folders i18n and libs should be exposed as volumes to allow resources and libraries customization
1. Multi-line arguments should be sorted alphanumerically: This will help to avoid duplication of packages and make the list much easier to update. This also makes PRs a lot easier to read and review
1. Add new label for versioning

**Comment by iromli** [comment]
PR has been merged.
